#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 11 15:04:52 CET 2023
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim game_logic_top_tb_behav -key {Behavioral:sim_1:Functional:game_logic_top_tb} -tclbatch game_logic_top_tb.tcl -view /home/mletemple/Documents/Cours/pokemon_silicium/src_vivado/Top_tb_behav.wcfg -log simulate.log"
xsim game_logic_top_tb_behav -key {Behavioral:sim_1:Functional:game_logic_top_tb} -tclbatch game_logic_top_tb.tcl -view /home/mletemple/Documents/Cours/pokemon_silicium/src_vivado/Top_tb_behav.wcfg -log simulate.log

